# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Tests_Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tests_Demo

  target 'Tests_DemoTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
  end

  target 'Tests_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
